version: '3'

services:
  app:  # spring boot application
    image: dhanushkamath/youtube-api:1.0.0
    depends_on: 
      - mongo
    restart: always
    environment: 
      - spring.data.mongodb.host=mongo
      - video.fetch.topic=cricket
      - video.fetch.interval=30000

    ports: 
      - '8080:8080' 

  mongo: # database
    image: mongo:4.2 
    ports:
      - '27017:27017'
    logging:
      driver: none # disable mongo logging