version: '3'

services:
  youtube-api-app:  # spring boot application
    image: dhanushkamath/youtube-api:1.0.0
    depends_on: 
      - mongo
    restart: always
    environment: 
      - api.key.list=<key1>,<key2>,<key3> # Replace key1, key2, key3 .. with api keys.
      - video.fetch.topic=cricket
      - video.fetch.interval=30000
      - spring.data.mongodb.host=mongo
    ports: 
      - '8080:8080' 

  mongo: # database
    image: mongo:4.2 
    ports:
      - '27017:27017'
    logging:
      driver: none # disable mongo logging